// [I-PLAN-MASTERGEN]［人が書く入力］AIプロファイルマスタ（[A-PROFILE-SCHEMA]）。
// 値の正本は [A-PROFILE-TABLE]。範囲は [I-PLAN-MILESTONE] M5（全24件）。
// weight_mult は小数第2位までの文字列で書き、生成時に centi へ変換する。
// 「─」は空辞書（weight_mult: {} / action_bonus: {}）として書く。

export const AI_PROFILES = [
  {
    profile_id: 'PROFILE_FRENZY',
    display_name: '狂乱',
    weight_mult: { impatience: '1.50', pp: '0.50' },
    action_bonus: { PASS: -800 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_ASSAULT',
    display_name: '強襲',
    weight_mult: { tempo: '1.50', position: '1.50' },
    action_bonus: { RUSH: 600, PASS: -600 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_COMMANDER',
    display_name: '将帥',
    weight_mult: { board: '2.00' },
    action_bonus: { SUMMON: 800 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_DRAIN_VP',
    display_name: '枯渇（VP）',
    weight_mult: {},
    action_bonus: { STRIP_VP: 900 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_DRAIN_PP',
    display_name: '枯渇（PP）',
    weight_mult: { tempo: '1.30' },
    action_bonus: { STRIP_PP: 900 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_SURGE',
    display_name: '波状',
    weight_mult: { board: '1.80', impatience: '1.50' },
    action_bonus: { SUMMON: 500 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_WALLBREAK',
    display_name: '破壁',
    weight_mult: {},
    action_bonus: { STRIP_AP: 1200 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_USHER',
    display_name: '差配',
    weight_mult: { position: '2.20', tempo: '1.20' },
    action_bonus: { INTERFERE: 900 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_TALLY',
    display_name: '計上',
    weight_mult: { pp: '1.50' },
    action_bonus: { SELF_HARM: 700 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_EXECUTION',
    display_name: '執行',
    weight_mult: { tempo: '2.00', pp: '1.50' },
    action_bonus: { HEAVY: 600 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_RELENTLESS',
    display_name: '不断',
    weight_mult: { tempo: '2.00', impatience: '1.20' },
    action_bonus: { PASS: -700 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_COMMANDER_BUFF',
    display_name: '将帥＋強化',
    weight_mult: { board: '2.00' },
    action_bonus: { SUMMON: 600, MIND: 300 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_INITIATIVE',
    display_name: '先手',
    weight_mult: { tempo: '1.80', survival: '1.20' },
    action_bonus: { RUSH: 500 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_AMBUSH',
    display_name: '伏勢',
    weight_mult: { tempo: '1.50', position: '1.60' },
    action_bonus: { HEAVY: 500 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_DEFENSE_STRONG',
    display_name: '防衛（強）',
    weight_mult: { position: '2.20' },
    action_bonus: { STANCE: 1000 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_EFFICIENCY',
    display_name: '効率',
    weight_mult: { pp: '1.80', impatience: '0.60' },
    action_bonus: { MIND: 400 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_SNIPE',
    display_name: '狙撃',
    weight_mult: { position: '2.50' },
    action_bonus: {},
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_CURSE',
    display_name: '呪縛',
    weight_mult: { debuff: '2.00' },
    action_bonus: { DEBUFF: 800 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_BULWARK',
    display_name: '鉄壁',
    weight_mult: { survival: '1.40', position: '1.60' },
    action_bonus: {},
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_DEFENSE',
    display_name: '防衛',
    weight_mult: { position: '2.00', impatience: '0.40' },
    action_bonus: { STANCE: 600 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_ASHBLIGHT',
    display_name: '灰蝕',
    weight_mult: { slip: '2.50', impatience: '1.50' },
    action_bonus: { SLIP: 1000 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_MIMIC',
    display_name: '模倣',
    weight_mult: { copy: '2.50', tempo: '1.20' },
    action_bonus: { COPY: 1000 },
    dynamic_weight: null,
  },
  {
    profile_id: 'PROFILE_MIRROR',
    display_name: '鏡像',
    weight_mult: { seal: '2.50' },
    action_bonus: { SEAL: 1000 },
    dynamic_weight: 'MIRROR_STATS',
  },
  {
    profile_id: 'PROFILE_TERMINUS',
    display_name: '終焉',
    weight_mult: {},
    action_bonus: {},
    dynamic_weight: null,
  },
];
